### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED (http://localhost:8080/graphql)

### ISSUE THREAD

**Issue by TheoMer** [apollographql/frontpage-react-app#4]
OS: Windows Pro 10
yarn: 0.21.3
npm:  3.8.6

1. Process
- git clone https://github.com/apollostack/frontpage-react-app
- cd frontpage-react-app
- yarn install
- npm start

2. What I expected to happen
For app to be launched on http://localhost:3000

3. What I actually saw
See attached image

What is the issue here?

![error](https://cloud.githubusercontent.com/assets/15969262/24139600/95ff31ec-0e14-11e7-91f8-652d912500c8.jpg)

**Comment by Lube** [comment]
From the readme:

Starting the app

This app talks to the hello world server, available here: https://github.com/apollostack/frontpage-server

Once you've installed and started that server, start this app with:

**Comment by stubailo** [comment]
Yeah, it looks like you are not running the server.
